### ISSUE TITLE
Clientside lua error

### ISSUE THREAD

**Issue by wrefgtzweve** [Grocel/3D-Stream-Radio#10]
Im not sure how to replicate this issue unfortunately. However i have the stack trace.
Players are getting this error pretty rarely but i thought, might as well report it.
```lua
addons/3d_stream_radio/lua/streamradio_core/tool.lua:15: attempt to call method 'GetToolObject' (a nil value)
  1. GetTool - addons/3d_stream_radio/lua/streamradio_core/tool.lua:15
   2. func - addons/3d_stream_radio/lua/streamradio_core/tool.lua:347
    3. unknown - addons/3d_stream_radio/lua/streamradio_core/timer.lua:36
```

**Comment by Grocel** [comment]
Thanks for report. It seems to happen on some rare edge case I would guess. Do you have an idea, what could have caused it? Like maybe the player still joining while like having the tool gun equipped?
