### ISSUE TITLE
UI Bugged First Time Opening Audio File

### ISSUE THREAD

**Issue by Peekofwar** [Grocel/3D-Stream-Radio#15]
I ran into a perculiar bug today when I went to touch Stream Radio... When I first open an audio file, the UI loads in in a buggy state. At first nothing appears wrong when you look at the interface and tooltips and button rollover effects work normally and display correct tooltips, however when you attempt to actually interract with them, it seems as though the buttons are not where they should be.

At first load of the stream player UI, the button order is as follows: `Pause, Stop, Decrease Volume, Increase Volume, Timeline, Back`.
![image](https://github.com/Grocel/3D-Stream-Radio/assets/10189526/ca518e3d-698b-4b51-959f-3f711b8efb72)
However, if you exit the player and then open the file again, the interface loads with this layout: `Pause, Stop, Previous Track, Next Track, Decrease Volume, Increase Volume, Loop Mode,, Timeline, Back`. This is the order in which interactions trigger even if the previous button order is displayed. 
![image](https://github.com/Grocel/3D-Stream-Radio/assets/10189526/97fd4896-878f-4ac6-88c1-a49864f1249f)

https://github.com/Grocel/3D-Stream-Radio/assets/10189526/e24bee37-a1d6-4614-9748-8c304f96bbee

For additional context: This bug was encountered whilst playing on a dedicated server that had just been restarted (also meaning all addons were freshly updated).

**Comment by Grocel** [comment]
Thanks of that well written report. The visuals confirms the addon to be up to date. I will try to fix this.

Apparently there is a networking issue, so the client is out of sync to the server when a playlist file is first opened per radio entity. When the radio opens a playlist file again, it will work properly for rest of the entity's existence.
