### ISSUE TITLE
Draw distance is not working properly

### ISSUE THREAD

**Issue by michak89** [Grocel/3D-Stream-Radio#23]
Hello there,
in entities/base_streamradio_gui.lua around line 1060, within this block:

```lua
if not self:CheckDistanceToEntity(ply, StreamRadioLib.GetDrawDistance(), nil, StreamRadioLib.GetCameraViewPos(ply)) then
	return 
end
``` 
For some reason, ply is not always me.
I haven't yet verified why this occurs, but it results in display rendering issues.

Initially, for about 2 minutes after joining the server, there are no issues with rendering and ply correctly refers to me.
However, after a while, another player on the server goes into this variable (bots also can), causing funny rendering problems.
Here is a video showing it:

https://youtu.be/G3uskHVfFzw

Adding ply = LocalPlayer() one line before the check seems to resolve it.
Sometimes ply can be even nil and draw distance works fine, stops rendering after set distance.
In singleplayer ply can only be one so it works perfect as it is there.

**Comment by Grocel** [comment]
Looks like there has been a global `ply` somewhere that gets inserted. Usually `ply` is `nil` and will resolve to `LocalPlayer()`. It is a bug, I will add the `LocalPlayer()` call as requested. The bug got visible after another addon added the ply global, likely by accident too. Thanks for reporting.

**Comment by Grocel** [comment]
Fixed in today's update.
