### ISSUE TITLE
Clientside load error preventing usage.

### ISSUE THREAD

**Issue by MuckerMayhem** [Grocel/3D-Stream-Radio#6]
```
[ERROR] addons/streamradio/lua/autorun/streamradio_loader.lua:529: attempt to concatenate field 'ErrorString' (a nil value)
  1. func - addons/streamradio/lua/autorun/streamradio_loader.lua:529
   2. unknown - lua/includes/extensions/net.lua:32
```

This error appears for any player joining the server, prevents anyone from spawning radios.

**Comment by Grocel** [comment]
Thanks for report, it should be showing the error currectly now. Keep in mind that this will not fix your actual error, as it is likely on your side.
